### ISSUE TITLE
problem installing htmrenamer

### ISSUE THREAD

**Issue by sarJess** [hmbotelho/htmrenamer#1]
HI, 

I'm really new to this. I tried installing the htmrenamer package. However, when I try installing it using the MacOS script in R, I get a warning error message:
Warning: invalid package ‘/path_to_file/htmrenamer_1.3.0.tar’
Error: ERROR: no packages specified
Warning message:
In install.packages("/path_to_file/htmrenamer_1.3.0.tar", repos = NULL,  :
  installation of package ‘/path_to_file/htmrenamer_1.3.0.tar’ had non-zero exit status

Can you please help me with this?

**Comment by hmbotelho** [comment]
Hi @sarJess ,

You should not write `/path_to_file/htmrenamer_1.3.0.tar` literally, but rather replace the text by the location of the `htmrenamer_1.3.0.tar` file on your computer. For example: `install.packages("/users/sarJess/desktop/htmrenamer_1.3.0.tar.gz", repos=NULL)`
